kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: pod-name-username
  labels:
    app: pod-label-username
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-label-username
  template:
    metadata:
      labels:
        app: pod-label-username
    spec:
      containers:
      - name: pod-container
        image: docker-hub-image-name:latest
        env:
          - name: ENVIRONMENT-VARIABLE-NAME
            value: environment-variable-value
        ports:
          - containerPort: 8080
          - containerPort: 8443
          - containerPort: 50000
        volumeMounts:
          - name: dockersock
            mountPath: "/var/run/docker.sock"
          - name: pod-volume-name
            mountPath: /var/pod-volume-name
      volumes:
      - name: pod-volume-name
        emptyDir: {}
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
